name: Build TF Lite Android Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      # 如有需要，下面这个步骤用于确保子模块被正确更新
      - name: Update Submodules (Optional)
        run: git submodule update --init --recursive

      - name: Install Bazelisk
        run: |
          # 下载适用于 Linux 的 Bazelisk 二进制文件
          curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x bazelisk
          # 将 Bazelisk 移动到 /usr/local/bin 并重命名为 bazel，使得后续调用 bazel 命令时由它接管
          sudo mv bazelisk /usr/local/bin/bazel
          echo "Bazel version:"
          bazel version

      - name: Build TF Lite Android Library
        run: |
          bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TF-Lite-android
          path: bazel-bin/**
